[global]
# dataFrameSerialization removido - n√£o mais suportado

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#881818"
backgroundColor = "#F8F8F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#202020"